---
- name: Deploy Calculator Docker container
  hosts: app_servers
  become: true
  tasks:

    - name: Pull latest calculator image
      community.docker.docker_image:
        name: avnlk/calculator
        tag: latest
        source: pull

    - name: Stop calculator container if running
      community.docker.docker_container:
        name: calculator
        state: stopped
        timeout: 10

    - name: Remove old container
      community.docker.docker_container:
        name: calculator
        state: absent
        force_kill: yes

    - name: Run calculator container
      community.docker.docker_container:
        name: calculator
        image: avnlk/calculator:latest
        state: started
        restart_policy: unless-stopped
        command: "/app/calculator"
        working_dir: "/app"
        detach: yes
        tty: yes
        stdin_open: yes   # required for interactive containers
