---
- name: Deploy Calculator Docker container
  hosts: app_servers
  become: true
  tasks:

    - name: Pull latest calculator image
      community.docker.docker_image:
        name: avnlk/calculator
        tag: latest
        source: pull

    - name: Remove old container if exists
      community.docker.docker_container:
        name: calculator
        state: absent
        force_kill: yes

    - name: Run calculator container
      community.docker.docker_container:
        name: calculator
        image: avnlk/calculator:latest
        state: started
        restart_policy: unless-stopped
        command: "./calculator"
        working_dir: "/app/build"
        tty: yes
